### ISSUE TITLE
User Creates an Account

### ISSUE THREAD

**Issue by dreid3** [RcVincent/Engineering-Society-of-York-Overhaul#6]
1. User clicks create account
2. User fills out account creation form and submits it.
3. User is automatically logged in as the user account they created. 

2a. User is notified if email supplied is already tied to an account and is not allowed to submit until unique email is supplied. 

Milestone: Minimal working system

**Comment by RcVincent** [comment]
I will take ownership of create account

**Comment by RcVincent** [comment]
Create account jsp set up but not fully working will continue to debug

**Comment by RcVincent** [comment]
It works in the new build
